In [1]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
from sklearn import metrics

In [2]:
Data = pd.read_csv('Shuffled_Feature_MalwareGoodware_Unweighted.csv',header=None,low_memory=False)
le = LabelEncoder()
Data_encoded = Data.apply(le.fit_transform)
Data_encoded.head()

0     1     2     3     4     5     6     7     8     9     ...   4600  \
0     1     0     0     0     0     0     0     0     0     0  ...      0   
1     1     0     0     0     0     0     0     0     0     0  ...      0   
2     2     0     0     0     0     0     0     0     0     0  ...      0   
3     1     0     0     0     0     0     0     0     0     0  ...      0   
4     2     1     1     1     1     1     1     1     1     1  ...      0   

   4601  4602  4603  4604  4605  4606  4607  4608  4609  
0     0     0     0     0     0     0     0     0     1  
1     0     0     0     0     0     0     0     0     1  
2     0     0     0     0     0     0     0     0     1  
3     0     0     0     0     0     0     0     0     0  
4     0     0     0     0     0     0     0     0     1  

[5 rows x 4610 columns]

In [3]:
Data_feature = Data_encoded.drop(Data_encoded.columns[4609],axis=1)

Result = Data_encoded[Data_encoded.columns[4609]]

#print(Data_feature.head())
#print("\n", Result.head())


In [4]:
Classifier = GaussianNB()

X_train, X_test, y_train, y_test = train_test_split(Data_feature, Result, test_size=0.3,random_state=109) #Split into Train and Test Set

Classifier.fit(X_train,y_train) # Train the Classifier using the training sets

Predicted_Result= Classifier.predict(X_test) #Predict Result
print(Predicted_Result)
#y_train.head(20)

[1 1 0 1 1 0 1 1 1 1 0 1 0 1 1 1 1 0 0 1 1 1 1 0 1 1 1 1 1 1 1 1 0 1 1 1 1
 1 1 0 1 1 1 0 1 1 1 1 1 1 0 0 1 1 1 0 1 0 0 1 0 1 0 1 1 1 0 1 1 1 0 0 1 1
 1 1 1 0 1 1 0 0 1 1 1 0 0 1 1 1 1 1 1 1 1 0 1 1 0 1 0 0 1 1 1 1 1 1 1 1 0
 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 0 1 1 1 0 0 1 1 0 1
 1 1 0 1 0 1 1 1 0 1 1 1 0 1 1 1 1 1 1 0 1 1 0 1 1 1 1 1 1 1 0 1 1 1 0 1 1
 1 1 1 0 1 0 1 1 1 1 0 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 0 1 0
 1 1 1 1 1 1 0 1 1 1 1 1 1 1 0 1 0 1 1 0 1 1 1 0 1 0 1 1 0 1 1 1 1 1 1 0 1
 0 1 1 1 0 1 1 1 1 1 1 1 1 1 0 1 1 0 1 1 0 1 1]


In [5]:
Accuracy = metrics.accuracy_score(y_test, Predicted_Result)*100
print("Accuracy ====>>", Accuracy," %")

Accuracy ====>> 74.11347517730496  %


In [6]:
print(metrics.classification_report(y_test, Predicted_Result))

              precision    recall  f1-score   support

           0       0.81      0.46      0.59       113
           1       0.72      0.93      0.81       169

   micro avg       0.74      0.74      0.74       282
   macro avg       0.77      0.69      0.70       282
weighted avg       0.76      0.74      0.72       282



In [7]:
print(metrics.precision_score(y_test, Predicted_Result)*100," %")

72.01834862385321  %


In [8]:
print(metrics.recall_score(y_test, Predicted_Result)*100," %")

92.89940828402366  %


In [25]:
# from sklearn.model_selection import KFold
# kf = KFold(n_splits=2)
# kf.get_n_splits(Data_feature)
# #print (kf)
# for train_index, test_index in kf.split(Data_feature):
#     #print("TRAIN:", train_index, "TEST:", test_index)

#     X_Train, X_Test = Data_feature[train_index], Data_feature[test_index]
#     #print(X_Train)
#     y_Train, y_Test = Result[train_index], Result[test_index]
#     Classifier.fit(X_Train, y_Train)
#     a = Classifier.predict(X_Test)
#     print (metrics.classification_report(y_Test, a))

ValueError: Found input variables with inconsistent numbers of samples: [939, 469]

In [9]:
from sklearn.model_selection import cross_val_score
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
print("Kfold Result Using GaussianNB : \n ")
print(cross_val_score(GaussianNB(),Data_feature,Result,cv=5))
print("\n Kfold Result Using SVC : \n ")
print(cross_val_score(SVC(),Data_feature,Result,cv=5))
print("\n Kfold Result Using RandomForest : \n ")
print(cross_val_score(RandomForestClassifier(n_estimators=40),Data_feature,Result,cv=5))

Kfold Result Using GaussianNB : 
 
[0.75       0.79255319 0.79255319 0.78191489 0.72192513]

 Kfold Result Using SVC : 
 


C:\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 

[0.75       0.78723404 0.78723404 0.78191489 0.72192513]

 Kfold Result Using RandomForest : 
 
[0.77659574 0.88297872 0.83510638 0.86702128 0.81283422]
