In [2]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
from sklearn import metrics

In [3]:
Data = pd.read_csv('Shuffled_Feature_MalwareGoodware_Weighted.csv',header=None,low_memory=False)
le = LabelEncoder()
Data_encoded = Data.apply(le.fit_transform)
Data_encoded

0     1     2     3     4     5     6     7     8     9     ...   3993  \
0       1     0     0     0     0     0     0     0     0     0  ...      0   
1       1     0     0     0     0     0     0     0     0     0  ...      0   
2       1     0     0     0     0     0     0     0     0     0  ...      0   
3       2     0     1     1     0     0     0     0     0     0  ...      0   
4       1     0     0     0     0     0     0     0     0     0  ...      0   
5       1     0     0     0     0     0     0     0     0     0  ...      0   
6       1     0     0     0     0     0     0     0     0     0  ...      0   
7       1     0     0     0     0     0     0     0     0     0  ...      0   
8       1     0     0     0     0     0     0     0     0     0  ...      0   
9       1     0     0     0     0     0     0     0     0     0  ...      0   
10      1     0     0     0     0     0     0     0     0     0  ...      0   
11      2     0     1     1     0     0     0     0     0     0  ...      0   
12      1     0     0     0     0     0     0     0     0     0  ...      0   
13      1     0     0     0     0     0     0     0     0     0  ...      0   
14      1     0     0     0     0     0     0     0     0     0  ...      0   
15      1     0     0     0     0     0     0     0     0     0  ...      0   
16      1     0     0     0     0     0     0     0     0     0  ...      0   
17      1     0     0     0     0     0     0     0     0     0  ...      0   
18      1     0     0     0     0     0     0     0     0     0  ...      0   
19      1     0     0     0     0     0     0     0     0     0  ...      0   
20      1     0     0     0     0     0     0     0     0     0  ...      0   
21      1     0     0     0     0     0     0     0     0     0  ...      0   
22      1     0     0     0     0     0     0     0     0     0  ...      0   
23      1     0     0     0     0     0     0     0     0     0  ...      0   
24      1     0     0     0     0     0     0     0     0     0  ...      0   
25      1     0     0     0     0     0     0     0     0     0  ...      0   
26      1     0     0     0     0     0     0     0     0     0  ...      0   
27      1     0     0     0     0     0     0     0     0     0  ...      0   
28      1     0     0     0     0     0     0     0     0     0  ...      0   
29      1     0     0     0     0     0     0     0     0     0  ...      0   
..    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...    ...   
894     1     0     0     0     0     0     0     0     0     0  ...      0   
895     1     0     0     0     0     0     0     0     0     0  ...      0   
896     1     0     0     0     0     0     0     0     0     0  ...      0   
897     1     0     0     0     0     0     0     0     0     0  ...      0   
898     1     0     0     0     0     0     0     0     0     0  ...      0   
899     1     0     0     0     0     0     0     0     0     0  ...      0   
900     1     0     0     0     0     0     0     0     0     0  ...      0   
901     1     0     0     0     0     0     0     0     0     0  ...      0   
902     1     0     1     1     0     0     0     0     0     0  ...      0   
903     1     0     0     0     0     0     0     0     0     0  ...      0   
904     1     0     0     0     0     0     0     0     0     0  ...      0   
905     1     0     0     0     0     0     0     0     0     0  ...      0   
906     1     0     0     0     0     0     0     0     0     0  ...      0   
907     1     0     0     0     0     0     0     0     0     0  ...      0   
908     1     0     0     0     0     0     0     0     0     0  ...      0   
909     1     0     0     0     0     0     0     0     0     0  ...      0   
910     1     0     0     0     0     0     0     0     0     0  ...      0   
911     1     0     0     0     0     0     0     0     0     0  ...      0   
912     1     0     0     0     0     0     0     0    

In [4]:
Data_feature = Data_encoded.drop(Data_encoded.columns[4002],axis=1)

Result = Data_encoded[Data_encoded.columns[4002]]

#print(Data_feature.head())
#print("\n", Result.head())

In [5]:
Classifier = GaussianNB()

X_train, X_test, y_train, y_test = train_test_split(Data_feature, Result, test_size=0.3,random_state=109) #Split into Train and Test Set

Classifier.fit(X_train,y_train) # Train the Classifier using the training sets

Predicted_Result= Classifier.predict(X_test) #Predict Result
print(Predicted_Result)
#y_train.head(20)

[0 1 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 1 0
 0 0 0 0 1 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 1 0 0 0
 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0
 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 1 0 1 1 0 1 1 0 0 0 0 0 0 0 0 0 0 0 1
 1 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 1 0 1 0 0 0 1 0
 0 0 0 1 1 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 1 0 0 0 1 0 0 1 0 0 0 0 0 0 0]


In [6]:
Accuracy = metrics.accuracy_score(y_test, Predicted_Result)*100
print("Accuracy ====>>", Accuracy," %")

Accuracy ====>> 66.54676258992805  %


In [7]:
print(metrics.classification_report(y_test, Predicted_Result))

              precision    recall  f1-score   support

           0       0.62      0.97      0.75       146
           1       0.90      0.33      0.49       132

   micro avg       0.67      0.67      0.67       278
   macro avg       0.76      0.65      0.62       278
weighted avg       0.75      0.67      0.63       278



In [8]:
print(metrics.precision_score(y_test, Predicted_Result)*100," %")

89.79591836734694  %


In [9]:
print(metrics.recall_score(y_test, Predicted_Result)*100," %")

33.33333333333333  %


In [14]:
from sklearn.model_selection import cross_val_score
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
print("Kfold Result Using GaussianNB : \n ")
print(cross_val_score(GaussianNB(),Data_feature,Result,cv=5))
print("\n Kfold Result Using SVC : \n ")
print(cross_val_score(SVC(),Data_feature,Result,cv=5))
print("\n Kfold Result Using RandomForest : \n ")
print(cross_val_score(RandomForestClassifier(n_estimators=40),Data_feature,Result,cv=5))

Kfold Result Using GaussianNB : 
 
[0.72043011 0.69189189 0.72432432 0.70652174 0.70652174]

 Kfold Result Using SVC : 
 


C:\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 

[0.55913978 0.56216216 0.56216216 0.55978261 0.55978261]

 Kfold Result Using RandomForest : 
 
[0.73655914 0.77297297 0.76216216 0.74456522 0.74456522]
